/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardTeachersRouteImport } from './routes/_dashboard.teachers'
import { Route as DashboardClassClassIdRouteImport } from './routes/_dashboard.class.$classId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeachersRoute = DashboardTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassClassIdRoute = DashboardClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/teachers': typeof DashboardTeachersRoute
  '/class/$classId': typeof DashboardClassClassIdRoute
}
export interface FileRoutesByTo {
  '/teachers': typeof DashboardTeachersRoute
  '/': typeof DashboardIndexRoute
  '/class/$classId': typeof DashboardClassClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/teachers': typeof DashboardTeachersRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/class/$classId': typeof DashboardClassClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/teachers' | '/class/$classId'
  fileRoutesByTo: FileRoutesByTo
  to: '/teachers' | '/' | '/class/$classId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/teachers'
    | '/_dashboard/'
    | '/_dashboard/class/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teachers': {
      id: '/_dashboard/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof DashboardTeachersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/class/$classId': {
      id: '/_dashboard/class/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof DashboardClassClassIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardTeachersRoute: typeof DashboardTeachersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClassClassIdRoute: typeof DashboardClassClassIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardTeachersRoute: DashboardTeachersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClassClassIdRoute: DashboardClassClassIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
